[features]
seeds = false
skip-lint = false

[programs.localnet]
treza_fee_splitter = "TRZAFeeSp1itterProgram111111111111111111111"

[programs.devnet]
treza_fee_splitter = "TRZAFeeSp1itterProgram111111111111111111111"

[programs.mainnet]
treza_fee_splitter = "TRZAFeeSp1itterProgram111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
